# Generated by Django 2.2.6 on 2023-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255)),
                ('ch_name', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('is_activate', models.BooleanField(default=True)),
                ('icon_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
